spring.datasource.url=jdbc:postgresql://localhost:5432/literalura_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# CORRECCIÓN: Dialecto para PostgreSQL (o puedes borrar la línea y Spring lo detecta solo)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Esto crea las tablas automáticamente basado en tus clases Libro y Autor
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola lo que está pasando en la base de datos
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.application.name=literalura
