# Cambia ${DB_HOST} y ${DB_NAME} por localhost y el nombre que creaste en pgAdmin
spring.datasource.url=jdbc:postgresql://localhost:5432/literalura_db
spring.datasource.username=postgres
spring.datasource.password=TU_PASSWORD_AQUI

spring.datasource.driver-class-name=org.postgresql.Driver

# CORRECCI�N: Dialecto para PostgreSQL (o puedes borrar la l�nea y Spring lo detecta solo)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Esto crea las tablas autom�ticamente basado en tus clases Libro y Autor
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola lo que est� pasando en la base de datos
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.application.name=literalura
